blank_issues_enabled: false
contact_links:
  - name: Arkanis Corporation Discord
    url: https://join.arkanis.cc
    about: If you have a question or want to talk to us, you can find us on our Discord server.
